from pydantic import BaseModel, Field, validator
from typing import Optional, List
from decimal import Decimal
from datetime import date

# ============= ORDER SCHEMAS =============

class OrderBase(BaseModel):
    """Base schema for Order data"""
    orderDate: date
    requiredDate: date
    shippedDate: Optional[date] = None
    status: str
    comments: Optional[str] = None


class OrderOut(OrderBase):
    """Schema for Order output (what user sees)"""
    orderNumber: int
    customerNumber: int
    
    class Config:
        from_attributes = True  # Allows Pydantic to work with SQLAlchemy models


# ============= PAYMENT SCHEMAS =============

class PaymentBase(BaseModel):
    """Base schema for Payment data"""
    paymentDate: date
    amount: Decimal


class PaymentOut(PaymentBase):
    """Schema for Payment output"""
    customerNumber: int
    checkNumber: str
    
    class Config:
        from_attributes = True


# ============= CUSTOMER SCHEMAS =============

class CustomerBase(BaseModel):
    """
    Base schema containing common fields.
    This is inherited by Create and Update schemas.
    """
    customerName: str = Field(..., min_length=1, max_length=50)
    contactLastName: str = Field(..., min_length=1, max_length=50)
    contactFirstName: str = Field(..., min_length=1, max_length=50)
    phone: str = Field(..., min_length=1, max_length=50)
    addressLine1: str = Field(..., min_length=1, max_length=50)
    addressLine2: Optional[str] = Field(None, max_length=50)
    city: str = Field(..., min_length=1, max_length=50)
    state: Optional[str] = Field(None, max_length=50)
    postalCode: Optional[str] = Field(None, max_length=15)
    country: str = Field(..., min_length=1, max_length=50)
    salesRepEmployeeNumber: Optional[int] = None
    creditLimit: Optional[Decimal] = None
    
    @validator('creditLimit')
    def validate_credit_limit(cls, v):
        """Ensure creditLimit is non-negative if provided"""
        if v is not None and v < 0:
            raise ValueError('Credit limit cannot be negative')
        return v


class CustomerCreate(CustomerBase):
    """
    Schema for creating a new customer.
    Inherits all fields from CustomerBase.
    customerNumber is auto-generated by database.
    """
    pass


class CustomerUpdate(BaseModel):
    """
    Schema for updating a customer.
    All fields are optional - user can update only what they want.
    """
    customerName: Optional[str] = Field(None, min_length=1, max_length=50)
    contactLastName: Optional[str] = Field(None, min_length=1, max_length=50)
    contactFirstName: Optional[str] = Field(None, min_length=1, max_length=50)
    phone: Optional[str] = Field(None, min_length=1, max_length=50)
    addressLine1: Optional[str] = Field(None, min_length=1, max_length=50)
    addressLine2: Optional[str] = Field(None, max_length=50)
    city: Optional[str] = Field(None, min_length=1, max_length=50)
    state: Optional[str] = Field(None, max_length=50)
    postalCode: Optional[str] = Field(None, max_length=15)
    country: Optional[str] = Field(None, min_length=1, max_length=50)
    salesRepEmployeeNumber: Optional[int] = None
    creditLimit: Optional[Decimal] = None
    
    @validator('creditLimit')
    def validate_credit_limit(cls, v):
        if v is not None and v < 0:
            raise ValueError('Credit limit cannot be negative')
        return v


class CustomerOut(CustomerBase):
    """
    Schema for customer output (what API returns).
    Includes customerNumber and related data.
    """
    customerNumber: int
    orders: List[OrderOut] = []  # List of customer's orders
    payments: List[PaymentOut] = []  # List of customer's payments
    
    class Config:
        from_attributes = True  # Allows conversion from SQLAlchemy models


class CustomerListOut(CustomerBase):
    """
    Simplified schema for listing customers (pagination).
    Doesn't include orders/payments to keep response lightweight.
    """
    customerNumber: int
    
    class Config:
        from_attributes = True